---
- name: Add Fish Repository
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3
    update_cache: true
  tags: fish

- name: Install Fish
  become: true
  ansible.builtin.apt:
    name: fish
    state: present
  tags: fish

- name: Set login shell
  become: true
  ansible.builtin.command: usermod --shell /usr/bin/fish {{ ansible_env.USER }}
  changed_when: false
  tags: fish
# curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
- name: Install omf when absent of fish user's home
  tags: fish
  block:
  - name: Get lastest Fisher from git
    ansible.builtin.git:
      repo: 'https://github.com/jorgebucaran/fisher'
      dest: '/tmp/fisher'
      clone: yes

  - name: Installing fisher for fish user
    ansible.builtin.shell: |
      source /tmp/fisher/functions/fisher.fish
      fisher install jorgebucaran/fisher
    args:
      executable: /usr/bin/fish

  - name: Cleanup fisher install files
    ansible.builtin.file:
      path: '/tmp/fisher'
      state: absent

  - name: Install fisher packages
    ansible.builtin.shell: |
      fisher install PatrickF1/colored_man_pages.fish
      fisher install edc/bass
      fisher install tillerburr/fish-autoenv
      fisher install jethrokuan/z
    args:
      executable: /usr/bin/fish
