---
- name: Add Fish Repository
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3
    update_cache: true
  tags: fish

- name: Install Fish
  become: true
  ansible.builtin.apt:
    name: fish
    state: present
  tags: fish

- name: Set login shell
  become: true
  ansible.builtin.command: usermod --shell /usr/bin/fish {{ ansible_env.USER }}
  changed_when: false
  tags: fish

- name: Install omf when absent of fish user's home
  tags: fish
  block:
  - name: Get lastest omf from git
    ansible.builtin.git:
      repo: 'https://github.com/oh-my-fish/oh-my-fish'
      dest: '/tmp/omf'
      clone: yes

  - name: Installing omf for fish user
    ansible.builtin.command: /tmp/omf/bin/install -y --offline --noninteractive

  - name: Cleanup omf install files
    ansible.builtin.file:
      path: '/tmp/omf'
      state: absent
  - name: Install omf packages
    ansible.builtin.shell: |
      omf install colored-man-pages
      omf install export
      omf install bass
      omf install z
      omf install https://github.com/dgrant/fish-autoenv2
    args:
      executable: /usr/bin/fish
