- name: Set up dev environment
  hosts: localhost
  vars:
    windows_user: tbaur
  vars_prompt:
    - name: gpg_passphrase
      prompt: "GPG passphrase"
      private: true

  pre_tasks:
  - name: Update apt
    become: true
    ansible.builtin.apt:
      update_cache: true
    when: ansible_os_family == 'Debian'

  tasks:
    - name: Core Utils
      tags: core
      import_role:
        name: core
      when: ansible_os_family == 'Debian'

    - name: ZSH
      tags: zsh
      import_role:
        name: zsh

    - name: Stow
      tags: stow
      import_role:
        name: stow

    - name: Fish Shell
      tags: fish
      import_role:
        name: fish
      when: ansible_os_family == 'Debian'

    - name: Mise-en-place
      tags: mise
      import_role:
        name: mise

    - name: rustup
      tags: rust
      import_role:
        name: rust
      when: ansible_os_family == 'Debian'

    - name: Neovim
      tags: neovim
      import_role:
        name: neovim
      when: ansible_os_family == 'Debian'

    - name: Terminal
      tags: terms
      import_role:
        name: terms
      when: ansible_os_family == 'Debian'

    - name: SSH
      tags: ssh
      import_role:
        name: ssh

    - name: GPG
      tags: gpg
      import_role:
        name: gpg

    - name: Tmux
      tags: tmux
      import_role:
        name: tmux

    - name: Claude Code
      tags: claude
      import_role:
        name: claude

    - name: Copy local git config
      copy:
        src: "./.gitconfig-local"
        dest: "{{ ansible_env.HOME }}/.gitconfig.local"

    - name: Copy xinitrc for WSLg Workaround
      copy:
        src: "./.xinitrc"
        dest: "{{ ansible_env.HOME }}/.xinitrc"
      when: ansible_os_family == 'Debian'
