- name: Install Core apt packages
  become: true
  ansible.builtin.apt:
    name:
      - git
      - python3
      - python3-venv
      - python3-pip
      - gnupg2
      - bat
      - python3-apt
      - thefuck
      - wget
      - curl
      - llvm
      - fzf
      - make
      - gcc
      - file
      - pinentry-tty
      - fd-find
      - build-essential
      - libssl-dev
      - libffi-dev
      - libbz2-dev
      - liblzma-dev
      - libncursesw5-dev
      - libreadline-dev
      - zlib1g-dev
      - libsqlite3-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
    state: present

- name: Add deadsnakes ppa
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Install Core apt packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - python3.12

- name: Create directory ~/.local/bin/
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: 0755

- name: Create link bat to batcat in Debian
  become: true
  ansible.builtin.file:
    src: '/usr/bin/batcat'
    dest: '/usr/bin/bat'
    state: link
- name: Create link fd to fdfind in Debian
  become: true
  ansible.builtin.file:
    src: '/usr/bin/fdfind'
    dest: '/usr/bin/fd'
    state: link
