- name: Install ZSH
  become: true
  ansible.builtin.package:
    name: zsh
    state: present

- name: Install zoxide
  become: true
  ansible.builtin.package:
    state: present
    name: zoxide

# required by the OMZ plugin zsh-interactive-cd
- name: Install fzf (command-line fuzzy finder)
  become: true
  ansible.builtin.package:
    state: present
    name: fzf

- name: Install Oh My Zsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Install zsh-autosuggestions plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1

- name: Install zsh-completions plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
    depth: 1

- name: Install zsh-syntax-highlighting plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zdharma-continuum/fast-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/fast-syntax-highlighting
    depth: 1

- name: Download catppuccin-frappe.ini from GitHub
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/catppuccin/zsh-fsh/main/themes/catppuccin-frappe.ini"
    dest: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(lookup('env', 'HOME') + '/.config') }}/catppuccin-frappe.ini"

- name: Change user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
