- name: Fetch mise-en-place
  when: ansible_os_family == 'Debian'
  ansible.builtin.uri:
    url: https://mise.jdx.dev/install.sh
    return_content: true
  register: mise_content

- name: Install mise-en-place
  when: ansible_os_family == 'Debian'
  ansible.builtin.shell:
    cmd: sh
    stdin: "{{ mise_content.content }}"


- name: Set mise binary path
  ansible.builtin.set_fact:
    mise_bin: "{{ '/opt/homebrew/bin/mise' if ansible_os_family == 'Darwin' else ansible_env.HOME + '/.local/bin/mise' }}"

- name: Install mise toolchains
  ansible.builtin.shell:
    cmd: |
      {{ mise_bin }} trust {{ansible_env.HOME}}/.config/.mise.toml
      {{ mise_bin }} install
  register: mise_install
  changed_when: "'all tools are installed' not in mise_install.stdout + mise_install.stderr"
