- name: move wezterm.lua to windows
  ansible.builtin.copy:
    src: files/.wezterm-wsl.lua
    dest: "/mnt/c/Users/{{windows_user}}/.wezterm.lua"
- name: create directory
  file:
    path: "/mnt/c/Users/{{windows_user}}/Powershell"
    state: directory
    
- name: move pwsh config
  ansible.builtin.copy:
    src: files/Microsoft.Powershell_profile.ps1
    dest: "/mnt/c/Users/{{windows_user}}/Powershell/Microsoft.Powershell_profile.ps1"

- name: move .wslconfig to windows
  ansible.builtin.copy:
    src: files/.wslconfig
    dest: "/mnt/c/Users/{{windows_user}}/.wslconfig"
  ignore_errors: True

- name: Install win32yank 64-bit from GitHub
  unarchive:
    src: https://github.com/equalsraf/win32yank/releases/download/v0.0.4/win32yank-x64.zip
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: true
    mode: "u+x"
    include:
      - win32yank.exe
