- name: Install Tmux
  become: true
  ansible.builting.apt:
    name: tmux


- name: Install TPM
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ansible_env.HOME}}/.tmux/plugins/tpm"
