[tools]
bun = "latest"
go = "latest"
node = "20"
poetry = "1.8.4"
python = "3.12"
rust = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
experimental = true
# disable_tools = ["python"]

[settings.python]
compile = false
