[tools]
nodejs=["18", "19"]
python = "3.12.1"
pnpm = "latest"
pdm = "latest"
java = "20.0.2"
pipx="latest"
go = "latest"
just = "latest"
node = "20"
zig = "latest"
poetry = "1.8.3"

[alias]
# specify a custom repo url
# note this will only be used if the plugin does not already exist
python = 'https://github.com/jdxcode/rtx-python'
pnpm ='https://github.com/jonathanmorley/asdf-pnpm'


[settings]
experimental = true
python_compile = false
