- name: Delete existing venv
  tags: python-venv
  file:
    path: "{{ansible_env.HOME}}/tools/.venv"
    state: absent

- name: Create python venv
  tags:
    - python-venv
    - install

  vars:
    mise: "{{ mise_bin | default(ansible_env.HOME + '/.local/bin/mise') }}"
    venv: "{{ ansible_env.HOME }}/tools/.venv"
  ansible.builtin.shell: |
    {{ mise }} exec uv -- uv venv --python 3.12 {{ venv }}
    {{ mise }} exec uv -- uv pip install --python {{ venv }}/bin/python -r {{ role_path }}/files/requirements.txt
