- name: Create python venv
  tags:
    - python-venv
    - install

  vars:
    mise: "{{ mise_bin | default(ansible_env.HOME + '/.local/bin/mise') }}"
    venv: "{{ ansible_env.HOME }}/tools/.venv"
  ansible.builtin.shell: |
    {{ mise }} exec uv -- uv venv --allow-existing --python 3.12 {{ venv }}
    {{ mise }} exec uv -- uv pip install --python {{ venv }}/bin/python -r {{ role_path }}/files/requirements.txt
  register: venv_install
  changed_when: "'Installed' in venv_install.stderr"
